<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Meja;
use App\Models\Kategori;
use App\Models\Produk;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Create Users
        User::firstOrCreate(
            ['email' => 'admin@pos.com'],
            [
                'name' => 'Administrator',
                'password' => Hash::make('password'),
                'role' => 'admin',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ]
        );

        User::firstOrCreate(
            ['email' => 'kasir@pos.com'],
            [
                'name' => 'Jane Kasir',
                'password' => Hash::make('password'),
                'role' => 'kasir',
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ]
        );

        // 2. Create Meja
        for ($i = 1; $i <= 5; $i++) {
            $meja = Meja::firstOrCreate(
                ['nomor_meja' => $i],
                ['qr_code' => null] // Will be auto-generated by the model or explicitly
            );
            $meja->generateQrCode();
        }

        // 3. Create Kategori
        $kategoriMakanan = Kategori::firstOrCreate(['nama_kategori' => 'Makanan Utama']);
        $kategoriMinuman = Kategori::firstOrCreate(['nama_kategori' => 'Minuman']);
        $kategoriSnack   = Kategori::firstOrCreate(['nama_kategori' => 'Cemilan']);

        // 4. Create Produk
        $produks = [
            // Makanan
            [
                'kategori_id'   => $kategoriMakanan->id,
                'nama_produk'   => 'Nasi Goreng Spesial',
                'gambar_produk' => 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80',
                'harga_produk'  => 25000,
                'ketersediaan'  => true,
            ],
            [
                'kategori_id'   => $kategoriMakanan->id,
                'nama_produk'   => 'Mie Goreng Seafood',
                'gambar_produk' => 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80',
                'harga_produk'  => 28000,
                'ketersediaan'  => true,
            ],
            [
                'kategori_id'   => $kategoriMakanan->id,
                'nama_produk'   => 'Ayam Penyet + Nasi',
                'gambar_produk' => 'https://images.unsplash.com/photo-1598515213692-b1f3e79e3e8c?w=400&q=80',
                'harga_produk'  => 22000,
                'ketersediaan'  => true,
            ],

            // Minuman
            [
                'kategori_id'   => $kategoriMinuman->id,
                'nama_produk'   => 'Es Teh Manis',
                'gambar_produk' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80',
                'harga_produk'  => 5000,
                'ketersediaan'  => true,
            ],
            [
                'kategori_id'   => $kategoriMinuman->id,
                'nama_produk'   => 'Es Jeruk',
                'gambar_produk' => 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&q=80',
                'harga_produk'  => 7000,
                'ketersediaan'  => true,
            ],
            [
                'kategori_id'   => $kategoriMinuman->id,
                'nama_produk'   => 'Kopi Susu Gula Aren',
                'gambar_produk' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80',
                'harga_produk'  => 15000,
                'ketersediaan'  => true,
            ],

            // Cemilan
            [
                'kategori_id'   => $kategoriSnack->id,
                'nama_produk'   => 'Kentang Goreng',
                'gambar_produk' => 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&q=80',
                'harga_produk'  => 12000,
                'ketersediaan'  => true,
            ],
            [
                'kategori_id'   => $kategoriSnack->id,
                'nama_produk'   => 'Pisang Bakar Coklat Keju',
                'gambar_produk' => 'https://images.unsplash.com/photo-1606851091748-9c9a874d9e0e?w=400&q=80',
                'harga_produk'  => 15000,
                'ketersediaan'  => true,
            ],
        ];

        foreach ($produks as $produk) {
            Produk::firstOrCreate(
                ['nama_produk' => $produk['nama_produk']],
                $produk
            );
        }
    }
}
